spring:
 profiles:
  active:
  - dev
---
spring:
 profiles: dev #开发环境配置
 application:
  name: microservicecloud-config-rainya-dev
---
spring:
 profiles: test #测试环境配置
 application:
  name: microservicecloud-config-rainya-test